name: ci-docker
on:
  pull_request:
    branches:
      - master

  # Runs on pushes targeting the default branch
  push:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    environment: DockerHub
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
#          - linux/arm/v7
#          - linux/arm64/v8
#          - linux/ppc64le
#          - linux/s390x

    env:
      DOCKERHUB_REPONAME: ps3dev
      DOCKERHUB_REPOTAG: latest
          
    steps:

      - name: Checkout
        uses: actions/checkout@v4    

      - name: README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPONAME }}
          provider: dockerhub
          short_description: 'A Docker Image for PS3 Development'
          readme_file: 'README.md'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPONAME }}:${{ env.DOCKERHUB_REPOTAG }}
